### ISSUE TITLE
where was the problem

### ISSUE THREAD

**Issue by urza** [dylandjian/SuperGo#4]
Hi,
I am wondering, did you figure out where was the problem with your program? Why was the agent playing so poorly?

**Comment by dylandjian** [comment]
Hello,

Sadly I was unable to pinpoint the exact cause as to why the agent was playing so poorly.
If I had to guess, it either comes from wrong hyperparameters (I couldn't use as many MCTS simulation as DeepMind : 128 instead of 1600 which reduces the exploration drastically) or from an implementation detail that I didn't catch.
